FROM python:3.10-slim AS development
 
WORKDIR /app/
 
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    python3-dev && \
    rm -rf /var/lib/apt/lists/*
 
 
RUN pip install --upgrade pip && \
    pip install --no-cache-dir uv
 
COPY pyproject.toml .
COPY .python-version .
 
 
RUN uv sync
 
 
COPY . .
 
# ARG APP_VERSION=1.0.0
# ENV APP_VERSION=${APP_VERSION}
# ENV PATH="/app/.venv/bin:$PATH"
# EXPOSE 8501
 
ENTRYPOINT ["python", "-m", "task_extract"]
 
